version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    image: ws_7_db_image
    container_name: usersdb7
  standalone:
    build:
      context: ./standalone
    image: ws_7_standalone_image
    container_name: standalone7
    links:
      - database
    depends_on:
      - database
    ports:
      - 9080:9080
      - 8000:8000
